// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaMC3nNP8gJpbzs_gjEWN-sxfGPUYo05I',
    appId: '1:186214489620:web:647818badda5061aa81101',
    messagingSenderId: '186214489620',
    projectId: 'civicconnect-7c316',
    authDomain: 'civicconnect-7c316.firebaseapp.com',
    databaseURL: 'https://civicconnect-7c316-default-rtdb.firebaseio.com',
    storageBucket: 'civicconnect-7c316.firebasestorage.app',
    measurementId: 'G-67XGD9K2D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyQrTQsh4Tu7Ayv4jrTHQVkAPxCjFQtjM',
    appId: '1:186214489620:android:82339eaa3018e5a5a81101',
    messagingSenderId: '186214489620',
    projectId: 'civicconnect-7c316',
    databaseURL: 'https://civicconnect-7c316-default-rtdb.firebaseio.com',
    storageBucket: 'civicconnect-7c316.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOTSnVdot8uMpVTD3BoiYUh1AR6N6-p6g',
    appId: '1:186214489620:ios:66611ad5d076a717a81101',
    messagingSenderId: '186214489620',
    projectId: 'civicconnect-7c316',
    databaseURL: 'https://civicconnect-7c316-default-rtdb.firebaseio.com',
    storageBucket: 'civicconnect-7c316.firebasestorage.app',
    iosBundleId: 'com.civicconnect.civicConnectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOTSnVdot8uMpVTD3BoiYUh1AR6N6-p6g',
    appId: '1:186214489620:ios:66611ad5d076a717a81101',
    messagingSenderId: '186214489620',
    projectId: 'civicconnect-7c316',
    databaseURL: 'https://civicconnect-7c316-default-rtdb.firebaseio.com',
    storageBucket: 'civicconnect-7c316.firebasestorage.app',
    iosBundleId: 'com.civicconnect.civicConnectMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaMC3nNP8gJpbzs_gjEWN-sxfGPUYo05I',
    appId: '1:186214489620:web:69a981c07e972476a81101',
    messagingSenderId: '186214489620',
    projectId: 'civicconnect-7c316',
    authDomain: 'civicconnect-7c316.firebaseapp.com',
    databaseURL: 'https://civicconnect-7c316-default-rtdb.firebaseio.com',
    storageBucket: 'civicconnect-7c316.firebasestorage.app',
    measurementId: 'G-NDYC2R96D0',
  );
}
